# Library

In [1]:
from skimage import feature
import numpy as np
import cv2

# Fungsi Local Binnary Pattern

In [2]:
# Local Binary Patterns (LBP) class
class LocalBinaryPatterns:
    def __init__(self, numPoints, radius):
        self.numPoints = numPoints
        self.radius = radius

    def describe(self, image):
        lbp = feature.local_binary_pattern(image, self.numPoints,
                                           self.radius, method="uniform")
        return lbp

# Inisiasi Local Binnary Pattern

In [3]:
# Inisialisasi objek LBP
lbp_descriptor = LocalBinaryPatterns(numPoints=8, radius=1)

# Contoh Local Binnary Pattern

In [4]:
# Baca citra
image = cv2.imread('Studi Kasus/Preprocessing Resize/00003 - Resized Image (9).jpg', cv2.IMREAD_GRAYSCALE)

In [5]:
# Cetak citra sebelum LBP dalam bentuk array
print("Citra sebelum LBP:")
print(image)

Citra sebelum LBP:
[[202 222 199 242 212 212 231 213 221]
 [225 226 201  52 213 205 210 226 226]
 [206 216 218 182 213 213 239 228 232]
 [223 219 210 207 234 220 238 224 227]
 [243 224 232  69 203 233 217 218 230]
 [225 234 235   0 222 222 225 217 206]
 [231 244 203  19 218 204 219 223 231]
 [242 218 244 231  28 232 207 223 235]
 [226 227 220 222 244  61 226 222 234]]


In [6]:
# Hitung LBP pada citra
lbp_result = lbp_descriptor.describe(image)

In [7]:
# Print hasil LBP
print("Hasil Local Binary Pattern:")
print(lbp_result)

Hasil Local Binary Pattern:
[[3. 1. 9. 0. 9. 9. 0. 5. 2.]
 [1. 0. 4. 8. 1. 8. 7. 4. 3.]
 [5. 9. 1. 5. 9. 6. 0. 9. 0.]
 [2. 4. 5. 9. 0. 9. 1. 6. 9.]
 [0. 6. 1. 7. 5. 0. 8. 9. 0.]
 [5. 9. 0. 8. 2. 9. 1. 7. 5.]
 [9. 0. 5. 7. 1. 7. 9. 3. 1.]
 [0. 8. 0. 1. 8. 0. 7. 4. 0.]
 [9. 9. 5. 9. 0. 5. 0. 9. 1.]]


# Add Histogram (Without Normalize)

In [8]:
# Local Binnary Patterns (LBP) class
class LocalBinaryPatternsHistogram:
    def __init__(self, numPoints, radius):
        self.numPoints = numPoints
        self.radius = radius

    def describe(self, image, eps=1e-7):
        lbp = feature.local_binary_pattern(image, self.numPoints,
                                           self.radius, method="uniform")
        (hist, _) = np.histogram(lbp.ravel(),
                                  bins=np.arange(0, self.numPoints + 3),
                                  range=(0, self.numPoints + 2))

        # Normalize the histogram
        #hist = hist.astype("float")
        #hist /= (hist.sum() + eps)

        return hist

In [9]:
# Inisialisasi objek LBP
lbp_descriptorH = LocalBinaryPatternsHistogram(numPoints=8, radius=1)

In [10]:
# Hitung LBP pada citra
lbp_resultH = lbp_descriptorH.describe(image)

In [11]:
# Print hasil LBP
print("Hasil Local Binary Pattern Histogram:")
print(lbp_resultH)

Hasil Local Binary Pattern Histogram:
[17 11  3  3  4 10  3  6  6 18]


# Local Binary Pattern Histogram With Normalize

In [12]:
# Local Binnary Patterns (LBP) class
class LocalBinaryPatternsHistogramFull:
    def __init__(self, numPoints, radius):
        self.numPoints = numPoints
        self.radius = radius

    def describe(self, image, eps=1e-7):
        lbp = feature.local_binary_pattern(image, self.numPoints,
                                           self.radius, method="uniform")
        (hist, _) = np.histogram(lbp.ravel(),
                                  bins=np.arange(0, self.numPoints + 3),
                                  range=(0, self.numPoints + 2))

        # Normalize the histogram
        hist = hist.astype("float")
        hist /= (hist.sum() + eps)

        return hist

In [13]:
# Inisialisasi objek LBP
lbp_descriptorF = LocalBinaryPatternsHistogramFull(numPoints=8, radius=1)

In [14]:
# Hitung LBP pada citra
lbp_resultF = lbp_descriptorF.describe(image)

In [15]:
# Print hasil LBP
print("Hasil Local Binary Pattern Histogram:")
print(lbp_resultF)

Hasil Local Binary Pattern Histogram:
[0.20987654 0.13580247 0.03703704 0.03703704 0.04938272 0.12345679
 0.03703704 0.07407407 0.07407407 0.22222222]
