# Library

In [1]:
# Import Library
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read Image

In [2]:
# Read the image
image = cv2.imread('Studi Kasus/Preprocessing Resize/00003 - Resized Image (4).jpg')

# Convert Image to Numerical Array

In [3]:
# Convert the image to a numerical array
image_array = np.array(image)

# Display Array

In [4]:
# Adjust NumPy printing options to display the full array
np.set_printoptions(threshold=np.inf)

# Display the array
print(image_array)

[[[249 249 235]
  [151 151 137]
  [235 235 221]
  [232 232 218]]

 [[229 229 215]
  [233 233 219]
  [230 230 216]
  [243 243 229]]

 [[249 249 237]
  [ 14  14   2]
  [244 244 232]
  [224 224 212]]

 [[237 237 225]
  [239 239 227]
  [245 245 233]
  [255 255 246]]]


In [5]:
# Print the shape of the array
print("\nShape:", image_array.shape)


Shape: (4, 4, 3)
